tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "automake"
brew "coreutils"
brew "libtool"
brew "asdf"
brew "xz"
brew "python@3.9"
brew "awscli"
brew "bundletool"
brew "glib"
brew "cairo"
brew "carthage"
brew "openldap"
brew "curl"
brew "fzf"
brew "gcc"
brew "gh"
brew "ghq"
brew "git"
brew "guile"
brew "gnutls"
brew "gnupg"
brew "gobject-introspection"
brew "graphviz"
brew "jq"
brew "libpq"
brew "mas"
brew "openapi-generator"
brew "swiftlint"
brew "terminal-notifier"
brew "tig"
brew "tree"
brew "xcodegen"
brew "yarn"
brew "zplug"
brew "zsh"
cask "adoptopenjdk8"
cask "alfred"
cask "android-studio"
cask "docker"
cask "dropbox"
cask "evernote"
cask "font-ricty-diminished"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "imageoptim"
cask "iterm2"
cask "notion"
cask "skitch"
cask "slack"
cask "visual-studio-code"
cask "xquartz"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "Apple Configurator 2", id: 1037126344
mas "Display Menu", id: 549083868
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
