tap "homebrew/core"
tap "homebrew/bundle"
tap "sanemat/font"
tap "caskroom/versions"
tap "caskroom/cask"
tap "mono0926/license-plist"
cask "xquartz"
brew "automake"
brew "carthage"
brew "colordiff"
brew "composer"
brew "fontforge"
brew "gcc"
brew "ghq"
brew "git"
brew "go"
brew "graphviz"
brew "hub"
brew "jq"
brew "mas"
brew "mitmproxy"
brew "nodebrew"
brew "peco"
brew "php"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "swiftlint"
brew "terminal-notifier"
brew "terraform"
brew "tig"
brew "tree"
brew "vim"
brew "watchman"
brew "yarn", args: ["without-node"]
brew "zplug"
brew "zsh"
brew "mono0926/license-plist/license-plist"
brew "sanemat/font/ricty"
cask "alfred"
cask "android-studio"
cask "arduino"
cask "atom"
cask "boostnote"
cask "chatwork"
cask "clipy"
cask "docker"
cask "dropbox"
cask "evernote"
cask "google-chrome"
cask "google-japanese-ime"
cask "imageoptim"
cask "iterm2"
cask "java"
cask "macdown"
cask "skitch"
cask "skype"
cask "slack"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "zeplin"
cask "zoomus"
cask "caskroom/versions/java8"
mas "1Password", id: 443987910
mas "Display Menu", id: 549083868
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
