tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mono0926/license-plist"
tap "sanemat/font"
brew "automake"
brew "readline", link: true
brew "sqlite"
brew "xz"
brew "carthage"
brew "colordiff"
brew "gcc"
brew "ghq"
brew "git"
brew "go"
brew "goenv"
brew "graphviz"
brew "hub"
brew "jq"
brew "mas"
brew "mitmproxy"
brew "nodebrew"
brew "peco"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "swiftlint"
brew "terminal-notifier"
brew "tig"
brew "tree"
brew "vim"
brew "xcodegen"
brew "yarn"
brew "zplug"
brew "zsh"
brew "mono0926/license-plist/license-plist"
brew "sanemat/font/ricty"
cask "alfred"
cask "android-studio"
cask "atom"
cask "docker"
cask "dropbox"
cask "evernote"
cask "google-chrome"
cask "google-japanese-ime"
cask "imageoptim"
cask "iterm2"
cask "skitch"
cask "slack"
cask "visual-studio-code"
cask "xquartz"
cask "zeplin"
cask "zoomus"
mas "1Password", id: 443987910
mas "Apple Configurator 2", id: 1037126344
mas "Display Menu", id: 549083868
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Xcode", id: 497799835
